# Variáveis e Objetos

In [1]:
x = 1
print(x)


1


In [2]:
y = 3.13
print(y)

3.13


In [3]:
#calculadora
x = 10
y = 20
z = 100
w = (x + y) * z / 100
print(w)

30.0


In [4]:
#verificar tipo
m = 'Python'
w = False

print(type(m))
print(type(w))

<class 'str'>
<class 'bool'>


In [5]:
#entrada de dados
print('Enter the value: ')
i = input()
# show string type
print(type(i))

Enter the value: 
5
<class 'str'>


In [6]:
# value entry with separate message and together
print('Enter the value: ')
i = input()
#or
i = input('Enter the value: ')

Enter the value: 
5
Enter the value: 4


In [7]:
# value conversion to integer

var = input('Enter the value: ')
print(type(var))
var = int(var)
print(type(var))

Enter the value: 44
<class 'str'>
<class 'int'>


In [8]:
# to float
var = input('Enter the value: ')
print(type(var))
var = float(var)
print(type(var))

Enter the value: 15
<class 'str'>
<class 'float'>


# Estrutura de Decisão

In [9]:
score = 7
if score >=7:
   print('Approved')
   print('Congratulations')
else:
  print('Fail')

Approved
Congratulations


In [10]:
score = 5
if score >=7:
   print('Approved')
   print('Congratulations')
else:
  print('Fail')

Fail


In [11]:
#Test with 4, 5 and 7
score = 4.5
if score >=7:
   print('Approved')
   print('Congratulations')
elif score > 4 and score <=6:
  print('Examination')
else:
  print('Fail')


Examination


# Estrutura de Repetição


In [12]:
# example with while
count = 1
while count <= 5:
  print(count)
  count +=1


1
2
3
4
5


In [13]:
# range (0, 10, 1):
# range (start, stop, increment)
# the python "ignores" the last value of intervals
#The increment may be negative

# for normal
for n in range(0, 10):
  print(n+1)

for n in range(1, 11):
  print(n)

1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


In [14]:
#for decrescente

for n in range(10, 0, -1):
  print(n)

10
9
8
7
6
5
4
3
2
1


In [15]:
#example with break
# will stop at 3 because the break is before the print
for n in range(0, 10):
  if n ==4:
    break
  print(n)

0
1
2
3


In [16]:
#example with continue
# will skip number 4
for n in range(0, 10):
  if n == 4:
    continue
  print(n)

0
1
2
3
5
6
7
8
9




# Listas

In [17]:
# ways to create lists
list1 = [1, 2, 3, 4, 5]
print(list1)

[1, 2, 3, 4, 5]


In [18]:
# different types
list2 = [1, 2, 3, '4', True]
print(list2)

[1, 2, 3, '4', True]


In [19]:
# List of List
list3 = [12, [1, 2, 3, 4, 5], 'a']
print(list3)

[12, [1, 2, 3, 4, 5], 'a']


In [20]:
# LIST LENGTH
print(len(list1))

5


In [21]:
# accessing element
print(list1[0])

# position 1 is a list
print(list3[1])

#changing position
list1[0] = 4
print(list1)

1
[1, 2, 3, 4, 5]
[4, 2, 3, 4, 5]


# Dicionários, Sets e Tuplas


In [22]:
# dictionaries: key/value
Notas = {'João': 6.0, 'Maria': 8.0, 'Pedro': 6.5}
print(Notas)

{'João': 6.0, 'Maria': 8.0, 'Pedro': 6.5}


In [23]:
print(Notas['João'])

6.0


In [24]:
# all keys
Notas.keys()

dict_keys(['João', 'Maria', 'Pedro'])

In [25]:
#logically tests for existence
print('João' in Notas)
print('Fernando' in Notas)

True
False


In [26]:
#all values
Notas.values()

dict_values([6.0, 8.0, 6.5])

In [27]:
#deletes an element

del Notas['João']
print(Notas)

{'Maria': 8.0, 'Pedro': 6.5}


In [28]:
# includes an element
Notas['Ana'] = 9
print(Notas)

{'Maria': 8.0, 'Pedro': 6.5, 'Ana': 9}


In [29]:
# searches for a value, if not found shows second parameter.
Notas.get('Ricardo, não localizado')
print(Notas)

{'Maria': 8.0, 'Pedro': 6.5, 'Ana': 9}


In [30]:
# sets! are unordered sets of unrepeated elements
bigdata = {'Spark', 'Hive', 'Sqoop'}
print(bigdata)

{'Spark', 'Hive', 'Sqoop'}


In [31]:
#checks for existence
print('Spark' in bigdata)

True


In [32]:
#adds elements
bigdata.add('Hadoop')
bigdata

{'Hadoop', 'Hive', 'Spark', 'Sqoop'}

In [33]:
# number of elements
print(len(bigdata))

4


In [34]:
bigdata.add('Spark')
bigdata

{'Hadoop', 'Hive', 'Spark', 'Sqoop'}

In [35]:
# tuples are lists that cannot be changed
# lists use [], tuples use ()
tupla = (1, 2, 3, 4, 5, 6, 7)
tupla

(1, 2, 3, 4, 5, 6, 7)

In [36]:
tupla[4]

5

In [37]:
#dictionaries where each position gets a tuple
dic2 = {(0,1 ): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 6, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
dic2

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 6,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

In [38]:
print(type(Notas))
print(type(bigdata))
print(type(tupla))

<class 'dict'>
<class 'set'>
<class 'tuple'>


# Numpy

In [39]:
import numpy as np

In [40]:
#create a single-dimension array;

mt = np.array([12, 34, 56, 75, 10, 18])
print(mt)
print(type(mt))

[12 34 56 75 10 18]
<class 'numpy.ndarray'>


In [41]:
# create the array with a specific type
# create the array as 64-bit float

mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint =  np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [42]:
#change the type of the array
#we can transform data types of arrays

mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)
# when we transform float to int the values are truncated
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [43]:
#we can do the reverse as well
mt5 = np.array([1, 2, 3, 4, 5])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [44]:
# more than one dimension
# creates a two-dimensional array

mt7 = np.array([[1, 2, 4], [12, 27, 3], [8, 9, 53]])
print(mt7)

[[ 1  2  4]
 [12 27  3]
 [ 8  9 53]]


In [45]:
#create typed empty arrays
# empty means that they are not initialized, not that they are empty
vazio = np.empty([3, 2], dtype = int)
print(vazio)
print("---------")

#creates a 4x3 matrix with zero values
zeros = np.zeros([4, 3])
print(zeros)
print('---------')

#with values equal to 1
one = np.ones([5, 7])
print(one)
print('--------')

#creates square matrix with main diagonal with values 1 and other values zero.
diagonal = np.eye(5)
print(diagonal)

[[100022429918752               0]
 [              0               0]
 [              0               0]]
---------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
--------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
# random values between 0 and 1
ale = np.random.random((5))
print(ale)
print('-----------------------------------------------')

# random values normal distribution containing negative
ale2 = np.random.randn((5))
print(ale2)
print('-----------------------------------------------')

# random values 3 x 4
ale3 = (10*np.random.random((3, 4)))
print(ale3)

[0.40304299 0.36822177 0.42972149 0.48919181 0.95657886]
-----------------------------------------------
[-2.21269775  1.38705077  0.72366425 -0.86642569  1.58762938]
-----------------------------------------------
[[7.01288277 1.79003447 6.41963089 2.81953121]
 [8.88244182 1.88863876 5.79662626 7.4525915 ]
 [8.50096401 8.63131718 7.32559096 0.36666461]]


In [47]:
#another way to generate random
#use of seed
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)
print('-----------------------------------------------')

#generate integers
ale6 = gnr.integers(10, size=(5, 4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
-----------------------------------------------
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]
 [0 0 8 7]
 [8 5 8 3]]


In [48]:
# unique removes repetitions
j= np.array([12, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [49]:
# specific functions
# create the two-dimensional matrix k
k = np.array([[17, 22, 43], [27, 25, 14], [15, 24, 32]])

# display the matrix k
print(k)

# show a specific element of the matrix k
print(k[0][1])

# show the size of the dimensions of the matrix k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [50]:
print(k)
# Mathematical Functions
# Show the largest value of the matrix k
print(k.max())
# Show the smallest value of matrix k
print(k.min())
# Shows the sum of the values of the matrix k
print((k.sum()))
# Show the average value of the values of the matrix k
print(k.mean())
# Show the value of the standard deviation of the values of the matrix k
print(k.std())

[[17 22 43]
 [27 25 14]
 [15 24 32]]
43
14
219
24.333333333333332
8.615231988880057


In [51]:
# Universal functions, applied to all elements
k1 = np.array([1, 4, 9, 16, 25, 36])
# Show the square root value of all elements
print(np.sqrt(k1))
# Show the exponential value of all elements
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [52]:
# Extraction of elements
m = np.array ([1, 2, 3, 4, 5, 6])
# Show the element of position 2
print(m[1])
# Show the array created from position 0, two elements
print(m[0:2])
print('------------')
# Show the array created from position 2 to the rest of the array
print(m[1:])
print('------------')
# Show the array created from the ante penultimate position to the end.
print(m[-3:])

2
[1 2]
------------
[2 3 4 5 6]
------------
[4 5 6]


In [53]:
# Extraction of rows and columns
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print('---------')

# First row, all columns
l_row_1 = l[0, :]
print(l_row_1)
print('---------')

# Second row
l_row_2 = l[1, :]
print(l_row_2)
print('---------')

#Third row
l_row_3 = l[2, :]
print(l_row_3)
print('---------')

# All rows, first column
l_column_1 = l[:, 0]
print(l_column_1)
print('---------')

# All rows, second column
l_column_2 = l[:, 1]
print(l_column_2)

[[4 5]
 [6 1]
 [7 4]]
---------
[4 5]
---------
[6 1]
---------
[7 4]
---------
[4 6 7]
---------
[5 1 4]


In [54]:
#Addition and multiplication of arrays
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])

resultado1 = n + o
print(resultado1)
print('----------')

resultado2 = n * o
print(resultado2)
print('----------')

p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
resultado3 = p + q
print(resultado3)


[[2 3]
 [4 5]]
----------
[[1 2]
 [3 4]]
----------
[[3 3]
 [5 5]
 [7 7]]


In [55]:
# Transposition, rearranges a set of 15 elements from 0 to 14 into 3 rows and 5 columns
f = np.arange(15).reshape((3, 5))
#Show the transposed array between row and column
print(f)
print('-----------')
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [56]:
# Another way to do it, same result
r = np.arange(15).reshape((3,5))
print(r)
# Rearrange a set of3 15 elements
# Show the matrix transposed between row and column
s = r.transpose((1, 0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [57]:
#Logical expressions
# Using where
# Creating array with positive and negative random values.
v = np.random.randn(4, 4)
print(v)
print('------------')

# Creating array with boolean values based on array v
x = (v > 0)
print(x)
print('----------')

# Creating array with values -1 and 1 based on array x values
z = np.where(x > 0, 1, -1)
print(z)

[[-2.0714364   0.90637911 -0.79868742 -0.29246956]
 [-1.89547855  1.60593315 -0.79670046  2.32941218]
 [ 0.68483598 -0.30256345  0.25272275  1.30133461]
 [-0.89274363  1.1565072   0.35050557 -0.07213441]]
------------
[[False  True False False]
 [False  True False  True]
 [ True False  True  True]
 [False  True  True False]]
----------
[[-1  1 -1 -1]
 [-1  1 -1  1]
 [ 1 -1  1  1]
 [-1  1  1 -1]]


# Pandas

In [2]:
import pandas as pd

In [3]:
# upload file to Pandas dataframe
url = ('https://raw.githubusercontent.com/tirolezzo/DataScience/main/Credit.csv')
dados = pd.read_csv(url)
# Format
dados.shape

(1000, 21)

In [4]:
#Statistical summary of numeric columns
dados.describe()

duration  credit_amount  installment_commitment  residence_since  \
count  1000.000000    1000.000000             1000.000000      1000.000000   
mean     20.903000    3271.258000                2.973000         2.845000   
std      12.058814    2822.736876                1.118715         1.103718   
min       4.000000     250.000000                1.000000         1.000000   
25%      12.000000    1365.500000                2.000000         2.000000   
50%      18.000000    2319.500000                3.000000         3.000000   
75%      24.000000    3972.250000                4.000000         4.000000   
max      72.000000   18424.000000                4.000000         4.000000   

               age  existing_credits  num_dependents  
count  1000.000000       1000.000000     1000.000000  
mean     35.546000          1.407000        1.155000  
std      11.375469          0.577654        0.362086  
min      19.000000          1.000000        1.000000  
25%      27.000000          1.000000        1.000000  
50%      33.000000          1.000000        1.000000  
75%      42.000000          2.000000        1.000000  
max      75.000000          4.000000        2.000000

In [5]:
#First records
dados.head()

checking_status  duration                    credit_history  \
0              <0         6  'critical/other existing credit'   
1        0<=X<200        48                   'existing paid'   
2   'no checking'        12  'critical/other existing credit'   
3              <0        42                   'existing paid'   
4              <0        24              'delayed previously'   

               purpose  credit_amount      savings_status employment  \
0             radio/tv           1169  'no known savings'        >=7   
1             radio/tv           5951                <100     1<=X<4   
2            education           2096                <100     4<=X<7   
3  furniture/equipment           7882                <100     4<=X<7   
4            'new car'           4870                <100     1<=X<4   

   installment_commitment       personal_status other_parties  ...  \
0                       4         'male single'          none  ...   
1                       2  'female div/dep/mar'          none  ...   
2                       2         'male single'          none  ...   
3                       2         'male single'     guarantor  ...   
4                       3         'male single'          none  ...   

    property_magnitude age  other_payment_plans     housing existing_credits  \
0        'real estate'  67                 none         own                2   
1        'real estate'  22                 none         own                1   
2        'real estate'  49                 none         own                1   
3     'life insurance'  45                 none  'for free'                1   
4  'no known property'  53                 none  'for free'                2   

                    job num_dependents  own_telephone foreign_worker class  
0               skilled              1            yes            yes  good  
1               skilled              1           none            yes   bad  
2  'unskilled resident'              2           none            yes  good  
3               skilled              2           none            yes  good  
4               skilled              2           none            yes   bad  

[5 rows x 21 columns]

In [6]:
#last records, with parameters
dados.tail(2)

checking_status  duration                    credit_history     purpose  \
998              <0        45                   'existing paid'    radio/tv   
999        0<=X<200        45  'critical/other existing credit'  'used car'   

     credit_amount savings_status  employment  installment_commitment  \
998           1845           <100      1<=X<4                       4   
999           4576     100<=X<500  unemployed                       3   

    personal_status other_parties  ...   property_magnitude age  \
998   'male single'          none  ...  'no known property'  23   
999   'male single'          none  ...                  car  27   

     other_payment_plans     housing existing_credits      job num_dependents  \
998                 none  'for free'                1  skilled              1   
999                 none         own                1  skilled              1   

     own_telephone foreign_worker class  
998            yes            yes   bad  
999           none            yes  good  

[2 rows x 21 columns]

In [7]:
#filter by column name
dados[['duration']]

duration
0           6
1          48
2          12
3          42
4          24
..        ...
995        12
996        30
997        12
998        45
999        45

[1000 rows x 1 columns]

In [8]:
#Filter rows by index
dados.loc[1:3]

checking_status  duration                    credit_history  \
1        0<=X<200        48                   'existing paid'   
2   'no checking'        12  'critical/other existing credit'   
3              <0        42                   'existing paid'   

               purpose  credit_amount savings_status employment  \
1             radio/tv           5951           <100     1<=X<4   
2            education           2096           <100     4<=X<7   
3  furniture/equipment           7882           <100     4<=X<7   

   installment_commitment       personal_status other_parties  ...  \
1                       2  'female div/dep/mar'          none  ...   
2                       2         'male single'          none  ...   
3                       2         'male single'     guarantor  ...   

   property_magnitude age  other_payment_plans     housing existing_credits  \
1       'real estate'  22                 none         own                1   
2       'real estate'  49                 none         own                1   
3    'life insurance'  45                 none  'for free'                1   

                    job num_dependents  own_telephone foreign_worker class  
1               skilled              1           none            yes   bad  
2  'unskilled resident'              2           none            yes  good  
3               skilled              2           none            yes  good  

[3 rows x 21 columns]

In [9]:
#rows 1 and 3
dados.loc[[1, 3]]

checking_status  duration   credit_history              purpose  \
1        0<=X<200        48  'existing paid'             radio/tv   
3              <0        42  'existing paid'  furniture/equipment   

   credit_amount savings_status employment  installment_commitment  \
1           5951           <100     1<=X<4                       2   
3           7882           <100     4<=X<7                       2   

        personal_status other_parties  ...  property_magnitude age  \
1  'female div/dep/mar'          none  ...       'real estate'  22   
3         'male single'     guarantor  ...    'life insurance'  45   

   other_payment_plans     housing existing_credits      job num_dependents  \
1                 none         own                1  skilled              1   
3                 none  'for free'                1  skilled              2   

   own_telephone foreign_worker class  
1           none            yes   bad  
3           none            yes  good  

[2 rows x 21 columns]

In [10]:
#filter
dados.loc[dados['purpose'] == 'radio/tv']

checking_status  duration                    credit_history   purpose  \
0                <0         6  'critical/other existing credit'  radio/tv   
1          0<=X<200        48                   'existing paid'  radio/tv   
8     'no checking'        12                   'existing paid'  radio/tv   
12         0<=X<200        12                   'existing paid'  radio/tv   
15               <0        24                   'existing paid'  radio/tv   
..              ...       ...                               ...       ...   
989        0<=X<200        24  'critical/other existing credit'  radio/tv   
991   'no checking'        15                        'all paid'  radio/tv   
992              <0        18                   'existing paid'  radio/tv   
997   'no checking'        12                   'existing paid'  radio/tv   
998              <0        45                   'existing paid'  radio/tv   

     credit_amount      savings_status employment  installment_commitment  \
0             1169  'no known savings'        >=7                       4   
1             5951                <100     1<=X<4                       2   
8             3059              >=1000     4<=X<7                       2   
12            1567                <100     1<=X<4                       1   
15            1282          100<=X<500     1<=X<4                       4   
..             ...                 ...        ...                     ...   
989           1743                <100        >=7                       4   
991           1569          100<=X<500        >=7                       4   
992           1936  'no known savings'     4<=X<7                       2   
997            804                <100        >=7                       4   
998           1845                <100     1<=X<4                       4   

          personal_status other_parties  ...   property_magnitude age  \
0           'male single'          none  ...        'real estate'  67   
1    'female div/dep/mar'          none  ...        'real estate'  22   
8          'male div/sep'          none  ...        'real estate'  61   
12   'female div/dep/mar'          none  ...                  car  22   
15   'female div/dep/mar'          none  ...                  car  32   
..                    ...           ...  ...                  ...  ..   
989         'male single'          none  ...     'life insurance'  48   
991         'male single'          none  ...                  car  34   
992        'male mar/wid'          none  ...                  car  23   
997         'male single'          none  ...                  car  38   
998         'male single'          none  ...  'no known property'  23   

     other_payment_plans     housing existing_credits                   job  \
0                   none         own                2               skilled   
1                   none         own                1               skilled   
8                   none         own                1  'unskilled resident'   
12                  none         own                1               skilled   
15                  none         own                1  'unskilled resident'   
..                   ...         ...              ...                   ...   
989                 none         own                2  'unskilled resident'   
991                 bank         own                1  'unskilled resident'   
992                 none        rent                2  'unskilled resident'   
997                 none         own                1               skilled   
998                 none  'for free'                1               skilled   

    num_dependents  own_telephone foreign_worker class  
0                1            yes            yes  good  
1                1           none            yes   bad  
8                1           none            yes  good  
12               1            yes            yes  good  
15               1           none          

In [11]:
# other condition
dados.loc[dados['credit_amount']> 18000]

checking_status  duration         credit_history purpose  credit_amount  \
915        0<=X<200        48  'no credits/all paid'   other          18424   

    savings_status employment  installment_commitment       personal_status  \
915           <100     1<=X<4                       1  'female div/dep/mar'   

    other_parties  ...  property_magnitude age  other_payment_plans housing  \
915          none  ...    'life insurance'  32                 bank     own   

    existing_credits                          job num_dependents  \
915                1  'high qualif/self emp/mgmt'              1   

     own_telephone foreign_worker class  
915            yes             no   bad  

[1 rows x 21 columns]

In [12]:
# assign result to variable, creating another df
credito2 = dados.loc[dados['credit_amount'] > 18000]
print(credito2)

    checking_status  duration         credit_history purpose  credit_amount  \
915        0<=X<200        48  'no credits/all paid'   other          18424   

    savings_status employment  installment_commitment       personal_status  \
915           <100     1<=X<4                       1  'female div/dep/mar'   

    other_parties  ...  property_magnitude age  other_payment_plans housing  \
915          none  ...    'life insurance'  32                 bank     own   

    existing_credits                          job num_dependents  \
915                1  'high qualif/self emp/mgmt'              1   

     own_telephone foreign_worker class  
915            yes             no   bad  

[1 rows x 21 columns]


In [13]:
# We define only a few columns
credito3 = dados[['checking_status', 'duration']].loc[dados['credit_amount'] > 18000]
print(credito3)

    checking_status  duration
915        0<=X<200        48


In [14]:
# Series, single column
# can be created, from lists, numpy array or Data frame column
s1 = pd.Series([2, 5, 9, 13, 34, 56, 89])
print(s1)

0     2
1     5
2     9
3    13
4    34
5    56
6    89
dtype: int64


In [15]:
# array from numpy array
import numpy as np
array1 = np.array([2, 5, 9, 13, 34, 56, 89])
s2 = pd.Series(array1)
print(s2)

0     2
1     5
2     9
3    13
4    34
5    56
6    89
dtype: int64


In [16]:
# series from a data frame
s3 = dados['purpose']
print(s3)
type(s3)

0                 radio/tv
1                 radio/tv
2                education
3      furniture/equipment
4                'new car'
              ...         
995    furniture/equipment
996             'used car'
997               radio/tv
998               radio/tv
999             'used car'
Name: purpose, Length: 1000, dtype: object


pandas.core.series.Series

In [17]:
# note the difference, we have the data frame
d4 = dados[['purpose']]
type(d4)

pandas.core.frame.DataFrame

In [21]:
#rename
dados_new = dados.rename(columns = {'duration': 'Duração', 'purpose': 'propósito'})
dados_new

checking_status  Duração                    credit_history  \
0                <0        6  'critical/other existing credit'   
1          0<=X<200       48                   'existing paid'   
2     'no checking'       12  'critical/other existing credit'   
3                <0       42                   'existing paid'   
4                <0       24              'delayed previously'   
..              ...      ...                               ...   
995   'no checking'       12                   'existing paid'   
996              <0       30                   'existing paid'   
997   'no checking'       12                   'existing paid'   
998              <0       45                   'existing paid'   
999        0<=X<200       45  'critical/other existing credit'   

               propósito  credit_amount      savings_status  employment  \
0               radio/tv           1169  'no known savings'         >=7   
1               radio/tv           5951                <100      1<=X<4   
2              education           2096                <100      4<=X<7   
3    furniture/equipment           7882                <100      4<=X<7   
4              'new car'           4870                <100      1<=X<4   
..                   ...            ...                 ...         ...   
995  furniture/equipment           1736                <100      4<=X<7   
996           'used car'           3857                <100      1<=X<4   
997             radio/tv            804                <100         >=7   
998             radio/tv           1845                <100      1<=X<4   
999           'used car'           4576          100<=X<500  unemployed   

     installment_commitment       personal_status other_parties  ...  \
0                         4         'male single'          none  ...   
1                         2  'female div/dep/mar'          none  ...   
2                         2         'male single'          none  ...   
3                         2         'male single'     guarantor  ...   
4                         3         'male single'          none  ...   
..                      ...                   ...           ...  ...   
995                       3  'female div/dep/mar'          none  ...   
996                       4        'male div/sep'          none  ...   
997                       4         'male single'          none  ...   
998                       4         'male single'          none  ...   
999                       3         'male single'          none  ...   

      property_magnitude age  other_payment_plans     housing  \
0          'real estate'  67                 none         own   
1          'real estate'  22                 none         own   
2          'real estate'  49                 none         own   
3       'life insurance'  45                 none  'for free'   
4    'no known property'  53                 none  'for free'   
..                   ...  ..                  ...         ...   
995        'real estate'  31                 none         own   
996     'life insurance'  40                 none         own   
997                  car  38                 none         own   
998  'no known property'  23                 none  'for free'   
999                  car  27                 none         own   

    existing_credits                          job num_dependents  \
0                  2                      skilled              1   
1                  1                      skilled              1   
2                  1         'unskilled resident'              2   
3                  1                      skilled              2   
4                  2                      skilled              2   
..               ...                          ...            ...   
995                1         'unskilled resident'              1   
996                1  'high qualif/self emp/mgmt'              1   
997                1                      skilled   

In [22]:
# But the change is not persisted
dados.head(1)

checking_status  duration                    credit_history   purpose  \
0              <0         6  'critical/other existing credit'  radio/tv   

   credit_amount      savings_status employment  installment_commitment  \
0           1169  'no known savings'        >=7                       4   

  personal_status other_parties  ...  property_magnitude age  \
0   'male single'          none  ...       'real estate'  67   

   other_payment_plans housing existing_credits      job num_dependents  \
0                 none     own                2  skilled              1   

   own_telephone foreign_worker class  
0            yes            yes  good  

[1 rows x 21 columns]

In [23]:
# To persist
dados.rename(columns = {'duration': 'Duração', 'purpose': 'propósito'}, inplace = True)

In [24]:
dados.head(1)

checking_status  Duração                    credit_history propósito  \
0              <0        6  'critical/other existing credit'  radio/tv   

   credit_amount      savings_status employment  installment_commitment  \
0           1169  'no known savings'        >=7                       4   

  personal_status other_parties  ...  property_magnitude age  \
0   'male single'          none  ...       'real estate'  67   

   other_payment_plans housing existing_credits      job num_dependents  \
0                 none     own                2  skilled              1   

   own_telephone foreign_worker class  
0            yes            yes  good  

[1 rows x 21 columns]

In [25]:
# delete column
dados.drop('checking_status', axis = 1, inplace = True)
print(dados)

     Duração                    credit_history            propósito  \
0          6  'critical/other existing credit'             radio/tv   
1         48                   'existing paid'             radio/tv   
2         12  'critical/other existing credit'            education   
3         42                   'existing paid'  furniture/equipment   
4         24              'delayed previously'            'new car'   
..       ...                               ...                  ...   
995       12                   'existing paid'  furniture/equipment   
996       30                   'existing paid'           'used car'   
997       12                   'existing paid'             radio/tv   
998       45                   'existing paid'             radio/tv   
999       45  'critical/other existing credit'           'used car'   

     credit_amount      savings_status  employment  installment_commitment  \
0             1169  'no known savings'         >=7                   

In [26]:
dados.head(1)

Duração                    credit_history propósito  credit_amount  \
0        6  'critical/other existing credit'  radio/tv           1169   

       savings_status employment  installment_commitment personal_status  \
0  'no known savings'        >=7                       4   'male single'   

  other_parties  residence_since property_magnitude  age other_payment_plans  \
0          none                4      'real estate'   67                none   

  housing  existing_credits      job  num_dependents own_telephone  \
0     own                 2  skilled               1           yes   

  foreign_worker class  
0            yes  good

In [27]:
# check null data
dados.isnull()

Duração  credit_history  propósito  credit_amount  savings_status  \
0      False           False      False          False           False   
1      False           False      False          False           False   
2      False           False      False          False           False   
3      False           False      False          False           False   
4      False           False      False          False           False   
..       ...             ...        ...            ...             ...   
995    False           False      False          False           False   
996    False           False      False          False           False   
997    False           False      False          False           False   
998    False           False      False          False           False   
999    False           False      False          False           False   

     employment  installment_commitment  personal_status  other_parties  \
0         False                   False            False          False   
1         False                   False            False          False   
2         False                   False            False          False   
3         False                   False            False          False   
4         False                   False            False          False   
..          ...                     ...              ...            ...   
995       False                   False            False          False   
996       False                   False            False          False   
997       False                   False            False          False   
998       False                   False            False          False   
999       False                   False            False          False   

     residence_since  property_magnitude    age  other_payment_plans  housing  \
0              False               False  False                False    False   
1              False               False  False                False    False   
2              False               False  False                False    False   
3              False               False  False                False    False   
4              False               False  False                False    False   
..               ...                 ...    ...                  ...      ...   
995            False               False  False                False    False   
996            False               False  False                False    False   
997            False               False  False                False    False   
998            False               False  False                False    False   
999            False               False  False                False    False   

     existing_credits    job  num_dependents  own_telephone  foreign_worker  \
0               False  False           False          False           False   
1               False  False           False          False           False   
2               False  False           False          False           False   
3               False  False           False          False           False   
4               False  False           False          False           False   
..                ...    ...             ...            ...             ...   
995             False  False           False          False           False   
996             False  False           False          False           False   
997             False  False           False          False           False   
998             False  False           False          False           False   
999             False  False           False          False           False   

     class  
0    False  
1    False  
2    False  
3    False  
4    False  
..     ...  
995  False  
996  False  
997  False  
998  False  
999  False  

[1000 rows x 20 columns]

In [28]:
#check null data
dados.isnull().sum()

Duração                   0
credit_history            0
propósito                 0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

In [29]:
# remove columns with NaN
dados.dropna()

Duração                    credit_history            propósito  \
0          6  'critical/other existing credit'             radio/tv   
1         48                   'existing paid'             radio/tv   
2         12  'critical/other existing credit'            education   
3         42                   'existing paid'  furniture/equipment   
4         24              'delayed previously'            'new car'   
..       ...                               ...                  ...   
995       12                   'existing paid'  furniture/equipment   
996       30                   'existing paid'           'used car'   
997       12                   'existing paid'             radio/tv   
998       45                   'existing paid'             radio/tv   
999       45  'critical/other existing credit'           'used car'   

     credit_amount      savings_status  employment  installment_commitment  \
0             1169  'no known savings'         >=7                       4   
1             5951                <100      1<=X<4                       2   
2             2096                <100      4<=X<7                       2   
3             7882                <100      4<=X<7                       2   
4             4870                <100      1<=X<4                       3   
..             ...                 ...         ...                     ...   
995           1736                <100      4<=X<7                       3   
996           3857                <100      1<=X<4                       4   
997            804                <100         >=7                       4   
998           1845                <100      1<=X<4                       4   
999           4576          100<=X<500  unemployed                       3   

          personal_status other_parties  residence_since   property_magnitude  \
0           'male single'          none                4        'real estate'   
1    'female div/dep/mar'          none                2        'real estate'   
2           'male single'          none                3        'real estate'   
3           'male single'     guarantor                4     'life insurance'   
4           'male single'          none                4  'no known property'   
..                    ...           ...              ...                  ...   
995  'female div/dep/mar'          none                4        'real estate'   
996        'male div/sep'          none                4     'life insurance'   
997         'male single'          none                4                  car   
998         'male single'          none                4  'no known property'   
999         'male single'          none                4                  car   

     age other_payment_plans     housing  existing_credits  \
0     67                none         own                 2   
1     22                none         own                 1   
2     49                none         own                 1   
3     45                none  'for free'                 1   
4     53                none  'for free'                 2   
..   ...                 ...         ...               ...   
995   31                none         own                 1   
996   40                none         own                 1   
997   38                none         own                 1   
998   23                none  'for free'                 1   
999   27                none         own                 1   

                             job  num_dependents own_telephone foreign_worker  \
0                        skilled               1           yes            yes   
1                        skilled               1          none            yes   
2           'unskilled resident'               2          none            yes   
3                        skilled               2          none            yes   
4                        skilled               2          none            yes   
..         

In [31]:
# fill in missing data
dados['Duração'].fillna(0,inplace = True)

In [32]:
#iloc
dados.iloc[0:3, 0:5]

Duração                    credit_history  propósito  credit_amount  \
0        6  'critical/other existing credit'   radio/tv           1169   
1       48                   'existing paid'   radio/tv           5951   
2       12  'critical/other existing credit'  education           2096   

       savings_status  
0  'no known savings'  
1                <100  
2                <100

In [33]:
dados.iloc[[0 ,1, 2, 3, 7], 0:5]

Duração                    credit_history            propósito  \
0        6  'critical/other existing credit'             radio/tv   
1       48                   'existing paid'             radio/tv   
2       12  'critical/other existing credit'            education   
3       42                   'existing paid'  furniture/equipment   
7       36                   'existing paid'           'used car'   

   credit_amount      savings_status  
0           1169  'no known savings'  
1           5951                <100  
2           2096                <100  
3           7882                <100  
7           6948                <100

# Módulos e Pacotes

In [34]:
import statistics
z = [10, 20, 30, 40]
x = statistics.mean(z)
y = statistics.median(z)
print(x)
print(y)

25
25.0


In [35]:
import statistics as est
z = [10, 20, 30, 40]
x = est.mean(z)
y = est.median(z)
print(x)
print(y)

25
25.0


In [38]:
from statistics import mean, median
z = [10, 20, 30, 40]
x = mean(z)
y = median(z)
print(x)
print(y)

25
25.0


In [39]:
from statistics import *
z = [10, 20, 30, 40]
x = mean(z)
y = median(z)
print(x)
print(y)

25
25.0


# Funções


In [41]:
def imprime():
  print('Aqui é uma função')
imprime()

Aqui é uma função


In [42]:
#with parameter
def imprime(n):
  print(n)

imprime('Impressão do texto')

Impressão do texto


In [43]:
#with return
def potencia(n):
  return n * n

x = potencia(3)
print(x)

9


In [50]:
# With default value
def intervalo(inic = 1, fim = 10):
  for n in range(1, fim + 1):
    print(n)

x  = intervalo(1, 10)

y = intervalo()

1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


# Fuções Padrão

In [57]:
# internal functions
print(abs(-200))
lst = [1, 2, 30, 30, 45]
print('Maior valor: ', max(lst))
print('Menor valor: ', min(lst))
print('Soma: ', sum(lst))
print('Arredeondamento: ', round(2.34567, 2))

200
Maior valor:  45
Menor valor:  1
Soma:  108
Arredeondamento:  2.35


In [59]:
#statistics
from statistics import *
print("Média: ", mean(lst))
print('Mediana: ', median(lst))
print('Moda: ', mode(lst))

Média:  21.6
Mediana:  30
Moda:  30


In [62]:
# Sample standard deviation
print('dexvio padrão: ', stdev(lst))

dexvio padrão:  19.346834366376324


In [63]:
#Sample variance
print('Variancia: ', variance(lst))

Variancia:  374.3


In [64]:
from numpy import *
a = random.random((8,8))
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[8.40706532e-01 9.23276065e-01 9.36322128e-01 6.00723832e-01
  1.79414718e-01 1.67209712e-01 8.08742443e-01 3.58133579e-01]
 [2.36531911e-01 1.45517721e-01 7.39519680e-01 7.78987147e-01
  8.71562551e-01 2.56621744e-01 5.10377887e-01 7.23044338e-01]
 [9.30475966e-01 7.71631063e-01 4.40058436e-01 8.27776422e-01
  2.46950380e-01 6.16887125e-02 1.87166558e-01 4.76621805e-01]
 [7.13835886e-01 3.85590012e-01 3.16730132e-01 8.14124683e-01
  2.22291466e-01 1.55338768e-01 8.39428091e-04 2.58058870e-01]
 [9.55711076e-01 6.53859377e-02 8.74553435e-01 5.22924912e-02
  6.37661034e-01 2.37122027e-01 8.91666242e-02 7.09972797e-01]
 [3.75098809e-01 4.89053883e-01 5.50754796e-01 6.78313677e-01
  7.49643358e-01 1.85029759e-01 8.01092312e-01 3.84221028e-01]
 [7.15658982e-01 3.84123444e-01 3.96738055e-01 3.93000197e-01
  8.39217603e-01 6.86312505e-01 1.78762108e-02 1.78867728e-01]
 [4.05228368e-01 9.89491253e-01 1.50664979e-01 1.66438349e-01
  3.26867424e-01 1.17209331e-01 9.40653

# Testes


In [2]:
# Faça um programa que tenha uma funçõa chamada amplitude. A função deve receber uma lista e imprimir a amplitude.
# crie tambem um código para testar sua função

def amplitude(vet):
  print('Amplitude: ', max(vet) - min(vet))

vetor = [12, 23, 45, 2, 100]
amplitude(vetor)

Amplitude:  98


In [4]:
# Faça uma função que receba uma string e imprima essa string na forma vertical
def imprime(texto):
  for n in range(0, len(texto)):
    print(texto[n])

imprime('Programador')

P
r
o
g
r
a
m
a
d
o
r


In [9]:
# Crie um progrma que lida o peso de uma carga em números inteiros.
# Se o peso for até 10 kg, informe que o valor será de R$ 50,00
# Entre 11 e 20 kg, informe que o valor será de R$ 80,00
# Se for maior que 20 informe que o transporte não pe aceito. Teste vários pesos.

peso = 20
if peso <=10:
  print('Valor da carga é de R$ 50,00')
elif peso >= 11 and peso <= 20:
  print('Valor da carga é de R$ 80,00')
else:
  print('O transporte não é aceito')


Valor da carga é de R$ 80,00
